name: Prepare Site
run-name: Preparing site
on:
  push:
    branches: ["master"]
jobs:
  Run-Build-Scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v3
        with: 
          submodules: 'true'
          
      - name: Set up python
        uses: actions/setup-python@v4
        with:
         python-version: '3.x' 
      - name: Install python dependencies
        run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
      - name: Install xelatex and dependencies
        run: | 
          sudo apt install -y  texlive-xetex
      - name: Run build actions
        run: |
          invoke quote
          invoke postall --replace
          invoke index
          cd Resume && python build.py
       
  
